# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'DavidUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(700, 550)
        Dialog.setStyleSheet("background-color: rgb(0, 0, 0);")
        Dialog.setModal(False)
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(2, -5, 331, 51))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("C:/Users/somes/OneDrive/Documents/Screenshot 2024-02-01 001513.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(10, 50, 311, 301))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("D:/DAVID GUI/Iron_Template_1.gif"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(320, 0, 381, 351))
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap("C:/Users/somes/Downloads/giphy.gif"))
        self.label_3.setScaledContents(True)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(0, 340, 321, 111))
        self.label_4.setText("")
        self.label_4.setPixmap(QtGui.QPixmap("D:/DAVID GUI/initial.gif"))
        self.label_4.setScaledContents(True)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(Dialog)
        self.label_5.setGeometry(QtCore.QRect(0, 420, 161, 131))
        self.label_5.setText("")
        self.label_5.setPixmap(QtGui.QPixmap("D:/DAVID GUI/Health_Template.gif"))
        self.label_5.setScaledContents(True)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(Dialog)
        self.label_6.setGeometry(QtCore.QRect(160, 430, 121, 121))
        self.label_6.setText("")
        self.label_6.setPixmap(QtGui.QPixmap("D:/DAVID GUI/B.G_Template_1.gif"))
        self.label_6.setScaledContents(True)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(Dialog)
        self.label_7.setGeometry(QtCore.QRect(280, 430, 121, 111))
        self.label_7.setText("")
        self.label_7.setPixmap(QtGui.QPixmap("D:/DAVID GUI/Code_Template.gif"))
        self.label_7.setScaledContents(True)
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(Dialog)
        self.label_8.setGeometry(QtCore.QRect(320, 350, 381, 81))
        self.label_8.setText("")
        self.label_8.setPixmap(QtGui.QPixmap("C:/Users/somes/Downloads/a064a7f04f9ecbf99cc543f1ba976adb69949e71_hq.gif"))
        self.label_8.setScaledContents(True)
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(Dialog)
        self.label_9.setGeometry(QtCore.QRect(400, 430, 141, 111))
        self.label_9.setText("")
        self.label_9.setPixmap(QtGui.QPixmap("D:/DAVID GUI/Jarvis_Gui (1).gif"))
        self.label_9.setScaledContents(True)
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(Dialog)
        self.label_10.setGeometry(QtCore.QRect(540, 430, 161, 121))
        self.label_10.setText("")
        self.label_10.setPixmap(QtGui.QPixmap("D:/DAVID GUI/Hero_Template.gif"))
        self.label_10.setScaledContents(True)
        self.label_10.setObjectName("label_10")
        self.pushButton = QtWidgets.QPushButton(Dialog)
        self.pushButton.setGeometry(QtCore.QRect(70, 320, 80, 24))
        self.pushButton.setStyleSheet("background-color: rgb(0, 85, 0);")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(Dialog)
        self.pushButton_2.setGeometry(QtCore.QRect(190, 320, 81, 24))
        self.pushButton_2.setStyleSheet("background-color: rgb(255, 0, 0);")
        self.pushButton_2.setObjectName("pushButton_2")
        self.textBrowser = QtWidgets.QTextBrowser(Dialog)
        self.textBrowser.setGeometry(QtCore.QRect(310, 0, 121, 31))
        self.textBrowser.setStyleSheet("background-color: transparent;\n"
"border-radius: none;")
        self.textBrowser.setObjectName("textBrowser")
        self.textBrowser_2 = QtWidgets.QTextBrowser(Dialog)
        self.textBrowser_2.setGeometry(QtCore.QRect(430, 0, 121, 31))
        self.textBrowser_2.setStyleSheet("background-color: transparent;\n"
"border-radius: none;")
        self.textBrowser_2.setObjectName("textBrowser_2")
        self.label_11 = QtWidgets.QLabel(Dialog)
        self.label_11.setGeometry(QtCore.QRect(10, 40, 111, 61))
        self.label_11.setText("")
        self.label_11.setPixmap(QtGui.QPixmap("D:/DAVID GUI/Earth_Template.gif"))
        self.label_11.setScaledContents(True)
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(Dialog)
        self.label_12.setGeometry(QtCore.QRect(200, 70, 101, 71))
        self.label_12.setText("")
        self.label_12.setPixmap(QtGui.QPixmap("D:/DAVID GUI/__1.gif"))
        self.label_12.setScaledContents(True)
        self.label_12.setObjectName("label_12")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        Dialog.setTabOrder(self.pushButton_2, self.pushButton)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.pushButton.setText(_translate("Dialog", "RUN"))
        self.pushButton_2.setText(_translate("Dialog", "TERMINATE"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
